spring:
  profiles:
    group:
      "local": "DB"
      "dev": "DB"
      "prod": "DB"

---

spring:
  config:
    activate:
      on-profile: "DB"
  datasource:
    platform: mysql
    url: ${DATASOURCE_URL_DB}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 9001